import type {
  Client,
  Lead,
  Member,
  Milestone,
  Project,
  Proposal,
  Review,
  Shoot,
  ShootStatus,
  Task,
  TaskComment,
} from "@/lib/studio/types";

export interface StudioSeed {
  members: Member[];
  clients: Client[];
  projects: Project[];
  milestones: Milestone[];
  tasks: Task[];
  comments: TaskComment[];
  leads: Lead[];
  proposals: Proposal[];
  shoots: Shoot[];
  reviews: Review[];
}

function day(offset: number, now: Date): string {
  const utc = Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate() + offset);
  return new Date(utc).toISOString().slice(0, 10);
}

function iso(offset: number, hour: number, now: Date): string {
  const utc = Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate() + offset, hour, 0, 0);
  return new Date(utc).toISOString();
}

/** Offset from today back to Monday, in UTC calendar days. */
function mondayOffset(now: Date): number {
  const dow = now.getUTCDay();
  const fromMonday = dow === 0 ? 6 : dow - 1;
  return -fromMonday;
}

/**
 * Curated memory snapshot in lunarcore-mcp shapes.
 * Client names follow the ClickUp Client Work folders. Project and task
 * copy is authored for the console — it is not a live export.
 * Contacts use example addresses. Nothing here is a ClickUp credential.
 */
export function createSeed(now = new Date()): StudioSeed {
  const members: Member[] = [
    {
      id: "mem_iris",
      name: "Iris Chen",
      email: "iris@lunarcore.studio",
      role: "Creative Director",
      active: true,
    },
    {
      id: "mem_julian",
      name: "Julian Park",
      email: "julian@lunarcore.studio",
      role: "Producer",
      active: true,
    },
    {
      id: "mem_nova",
      name: "Nova Reyes",
      email: "nova@lunarcore.studio",
      role: "Editor",
      active: true,
    },
  ];

  const clients: Client[] = [
    {
      id: "cli_kobelco",
      name: "Kobelco",
      status: "active",
      industry: "Equipment",
      primaryContact: { name: "Ren Sato", email: "ren@kobelco.example" },
      notes: "Machine films need a clean site and no talent releases on the floor.",
      createdAt: iso(-40, 9, now),
      updatedAt: iso(0, 8, now),
    },
    {
      id: "cli_banwa",
      name: "Banwa Wellness Spa",
      status: "active",
      industry: "Wellness",
      primaryContact: { name: "Amina Cruz", email: "amina@banwa.example" },
      notes: "Quiet luxury. Natural light, no voiceover, warm stone and water.",
      createdAt: iso(-60, 9, now),
      updatedAt: iso(-1, 16, now),
    },
    {
      id: "cli_visa_au",
      name: "Visa Alliance Australia",
      status: "active",
      industry: "Professional services",
      primaryContact: { name: "Helen Ward", email: "helen@visa-alliance.example" },
      notes: "Explainer must stay plain-language. Legal reviews every super before picture lock.",
      createdAt: iso(-30, 9, now),
      updatedAt: iso(-1, 11, now),
    },
    {
      id: "cli_bp",
      name: "BP Boiling Crabs & Shrimps",
      status: "active",
      industry: "Restaurant",
      primaryContact: { name: "Marco Dela Cruz", email: "marco@bpboiling.example" },
      notes: "Weekend boil reads loud: steam, hands, and a short price end card.",
      createdAt: iso(-50, 9, now),
      updatedAt: iso(-2, 15, now),
    },
    {
      id: "cli_kendi",
      name: "Kendi Beauty Lounge & Wellness",
      status: "active",
      industry: "Beauty",
      primaryContact: { name: "Lila Santos", email: "lila@kendi.example" },
      notes: "Lounge launch. Skin texture stays honest. No heavy beauty retouch.",
      createdAt: iso(-20, 9, now),
      updatedAt: iso(-3, 13, now),
    },
    {
      id: "cli_fivestar",
      name: "Five Star Stays",
      status: "active",
      industry: "Travel",
      primaryContact: { name: "Jonah Hale", email: "jonah@fivestarstays.example" },
      notes: "Property films. Dawn exteriors, then interiors with the lights they actually use.",
      createdAt: iso(-15, 9, now),
      updatedAt: iso(-4, 10, now),
    },
    {
      id: "cli_crazy",
      name: "Crazy Curry",
      status: "active",
      industry: "Restaurant",
      primaryContact: { name: "Priya Nair", email: "priya@crazycurry.example" },
      notes: "Brand spots in review. Heat and color first, offer second.",
      createdAt: iso(-25, 9, now),
      updatedAt: iso(-5, 12, now),
    },
    {
      id: "cli_mori",
      name: "Mori & Mill",
      status: "active",
      industry: "Hospitality",
      primaryContact: { name: "Elise Moreau", email: "elise@moriandmill.example" },
      notes: "Seasonal menu film is delivered. Calendar work continues weekly.",
      createdAt: iso(-70, 9, now),
      updatedAt: iso(-6, 9, now),
    },
    {
      id: "cli_coffee",
      name: "Coffee Dome",
      status: "paused",
      industry: "Cafe",
      primaryContact: { name: "Sam Ortiz", email: "sam@coffeedome.example" },
      notes: "Paused while the menu locks. Photography resumes on the new board.",
      createdAt: iso(-45, 9, now),
      updatedAt: iso(-12, 9, now),
    },
    {
      id: "cli_internal",
      name: "Lunarcore Internal",
      status: "active",
      industry: "Studio",
      notes: "House work. Not a client folder in spirit, still a Client Work folder.",
      createdAt: iso(-10, 9, now),
      updatedAt: iso(-8, 9, now),
    },
    {
      id: "cli_vesper",
      name: "Vesper Ceramics",
      status: "prospect",
      industry: "Ceramics",
      primaryContact: { name: "June Pell", email: "june@vesper.example" },
      notes: "Qualified lead from the memory stub. Wants a brand film for spring. No project yet.",
      createdAt: iso(-4, 9, now),
      updatedAt: iso(-4, 9, now),
    },
  ];

  const projects: Project[] = [
    {
      id: "prj_kobelco_film",
      clientId: "cli_kobelco",
      name: "Site machine film",
      status: "active",
      phase: "Production",
      startDate: day(-12, now),
      dueDate: day(16, now),
      description: "60s machine film and a 15s cutdown for the current site range.",
      createdAt: iso(-12, 9, now),
      updatedAt: iso(0, 8, now),
    },
    {
      id: "prj_kobelco_stills",
      clientId: "cli_kobelco",
      name: "Product stills",
      status: "active",
      phase: "Production",
      startDate: day(-6, now),
      dueDate: day(20, now),
      description: "Hero stills on a neutral ground, plus detail crops for the catalogue.",
      createdAt: iso(-6, 9, now),
      updatedAt: iso(-2, 9, now),
    },
    {
      id: "prj_banwa_film",
      clientId: "cli_banwa",
      name: "Ritual film series",
      status: "active",
      phase: "Post",
      startDate: day(-21, now),
      dueDate: day(14, now),
      description: "Three short rituals. 45s master each, no voiceover.",
      createdAt: iso(-21, 9, now),
      updatedAt: iso(-1, 16, now),
    },
    {
      id: "prj_banwa_content",
      clientId: "cli_banwa",
      name: "Always-on content",
      status: "active",
      phase: "Production",
      startDate: day(-10, now),
      dueDate: day(24, now),
      description: "Weekly stills and a story set from the treatment room.",
      createdAt: iso(-10, 9, now),
      updatedAt: iso(-3, 9, now),
    },
    {
      id: "prj_visa_explainer",
      clientId: "cli_visa_au",
      name: "Partner explainer",
      status: "active",
      phase: "Post",
      startDate: day(-18, now),
      dueDate: day(11, now),
      description: "90s explainer for partner clinics. Legal holds picture lock.",
      createdAt: iso(-18, 9, now),
      updatedAt: iso(-1, 11, now),
    },
    {
      id: "prj_bp_promo",
      clientId: "cli_bp",
      name: "Weekend boil promo",
      status: "active",
      phase: "Post",
      startDate: day(-9, now),
      dueDate: day(6, now),
      description: "15s and 6s cutdowns for the weekend boil, plus a still end card.",
      createdAt: iso(-9, 9, now),
      updatedAt: iso(-2, 15, now),
    },
    {
      id: "prj_bp_ads",
      clientId: "cli_bp",
      name: "Always-on ads",
      status: "active",
      phase: "Production",
      startDate: day(-4, now),
      dueDate: day(18, now),
      description: "Static and motion variants for the standing offer.",
      createdAt: iso(-4, 9, now),
      updatedAt: iso(-2, 12, now),
    },
    {
      id: "prj_kendi_launch",
      clientId: "cli_kendi",
      name: "Lounge launch",
      status: "active",
      phase: "Production",
      startDate: day(-8, now),
      dueDate: day(19, now),
      description: "Launch film, portrait set, and the opening-week stories.",
      createdAt: iso(-8, 9, now),
      updatedAt: iso(-3, 13, now),
    },
    {
      id: "prj_fivestar_films",
      clientId: "cli_fivestar",
      name: "Property films",
      status: "active",
      phase: "Production",
      startDate: day(-5, now),
      dueDate: day(28, now),
      description: "Two property films. Dawn exterior, then the rooms as a guest finds them.",
      createdAt: iso(-5, 9, now),
      updatedAt: iso(-4, 10, now),
    },
    {
      id: "prj_crazy_spots",
      clientId: "cli_crazy",
      name: "Brand spots",
      status: "review",
      phase: "Review",
      startDate: day(-16, now),
      dueDate: day(3, now),
      description: "Two brand spots in client review. Heat, color, then the offer.",
      createdAt: iso(-16, 9, now),
      updatedAt: iso(-5, 12, now),
    },
    {
      id: "prj_mori_menu",
      clientId: "cli_mori",
      name: "Seasonal menu film",
      status: "delivered",
      phase: "Delivered",
      startDate: day(-40, now),
      dueDate: day(-6, now),
      description: "Delivered seasonal menu film and stills.",
      createdAt: iso(-40, 9, now),
      updatedAt: iso(-6, 9, now),
    },
    {
      id: "prj_mori_calendar",
      clientId: "cli_mori",
      name: "Content calendar",
      status: "active",
      phase: "Production",
      startDate: day(-7, now),
      dueDate: day(21, now),
      description: "The standing weekly calendar after the menu film.",
      createdAt: iso(-7, 9, now),
      updatedAt: iso(-6, 10, now),
    },
    {
      id: "prj_coffee_menu",
      clientId: "cli_coffee",
      name: "Menu photography",
      status: "on_hold",
      phase: "Planning",
      startDate: day(7, now),
      dueDate: day(35, now),
      description: "On hold until the new menu board is signed.",
      createdAt: iso(-14, 9, now),
      updatedAt: iso(-12, 9, now),
    },
    {
      id: "prj_internal_os",
      clientId: "cli_internal",
      name: "Studios OS",
      status: "planning",
      phase: "Discovery",
      startDate: day(0, now),
      dueDate: day(45, now),
      description: "Internal console for the floor. This build is the first cut.",
      createdAt: iso(-3, 9, now),
      updatedAt: iso(-3, 9, now),
    },
  ];

  const milestones: Milestone[] = [
    {
      id: "mls_kobelco_shoot",
      projectId: "prj_kobelco_film",
      name: "Site shoot",
      status: "blocked",
      dueDate: day(4, now),
      description: "Waiting on site access and a safety induction.",
      createdAt: iso(-12, 9, now),
      updatedAt: iso(0, 8, now),
    },
    {
      id: "mls_kobelco_cut",
      projectId: "prj_kobelco_film",
      name: "Picture lock",
      status: "pending",
      dueDate: day(14, now),
      createdAt: iso(-12, 9, now),
      updatedAt: iso(-6, 9, now),
    },
    {
      id: "mls_kobelco_stills",
      projectId: "prj_kobelco_stills",
      name: "Selects",
      status: "in_progress",
      dueDate: day(9, now),
      createdAt: iso(-6, 9, now),
      updatedAt: iso(-2, 9, now),
    },
    {
      id: "mls_banwa_rough",
      projectId: "prj_banwa_film",
      name: "Rough cut",
      status: "in_progress",
      dueDate: day(-2, now),
      description: "Internal rough cut. Date has slipped.",
      createdAt: iso(-21, 9, now),
      updatedAt: iso(-1, 16, now),
    },
    {
      id: "mls_banwa_final",
      projectId: "prj_banwa_film",
      name: "Final delivery",
      status: "pending",
      dueDate: day(14, now),
      createdAt: iso(-21, 9, now),
      updatedAt: iso(-10, 9, now),
    },
    {
      id: "mls_banwa_week",
      projectId: "prj_banwa_content",
      name: "This week's set",
      status: "in_progress",
      dueDate: day(4, now),
      createdAt: iso(-10, 9, now),
      updatedAt: iso(-1, 9, now),
    },
    {
      id: "mls_visa_legal",
      projectId: "prj_visa_explainer",
      name: "Legal review",
      status: "blocked",
      dueDate: day(2, now),
      description: "Picture lock waits on the marked-up script.",
      createdAt: iso(-18, 9, now),
      updatedAt: iso(-1, 11, now),
    },
    {
      id: "mls_visa_lock",
      projectId: "prj_visa_explainer",
      name: "Picture lock",
      status: "pending",
      dueDate: day(9, now),
      createdAt: iso(-18, 9, now),
      updatedAt: iso(-8, 9, now),
    },
    {
      id: "mls_bp_cuts",
      projectId: "prj_bp_promo",
      name: "Cutdowns",
      status: "pending",
      dueDate: day(-3, now),
      description: "15s and 6s were due earlier this week.",
      createdAt: iso(-9, 9, now),
      updatedAt: iso(-2, 15, now),
    },
    {
      id: "mls_bp_ads",
      projectId: "prj_bp_ads",
      name: "Variant set",
      status: "in_progress",
      dueDate: day(8, now),
      createdAt: iso(-4, 9, now),
      updatedAt: iso(-2, 12, now),
    },
    {
      id: "mls_kendi_portraits",
      projectId: "prj_kendi_launch",
      name: "Portrait set",
      status: "in_progress",
      dueDate: day(7, now),
      createdAt: iso(-8, 9, now),
      updatedAt: iso(-3, 13, now),
    },
    {
      id: "mls_kendi_film",
      projectId: "prj_kendi_launch",
      name: "Launch film",
      status: "pending",
      dueDate: day(16, now),
      createdAt: iso(-8, 9, now),
      updatedAt: iso(-3, 13, now),
    },
    {
      id: "mls_fivestar_dawn",
      projectId: "prj_fivestar_films",
      name: "Dawn exteriors",
      status: "pending",
      dueDate: day(10, now),
      createdAt: iso(-5, 9, now),
      updatedAt: iso(-4, 10, now),
    },
    {
      id: "mls_crazy_review",
      projectId: "prj_crazy_spots",
      name: "Client review",
      status: "in_progress",
      dueDate: day(2, now),
      createdAt: iso(-16, 9, now),
      updatedAt: iso(-5, 12, now),
    },
    {
      id: "mls_mori_delivered",
      projectId: "prj_mori_menu",
      name: "Final delivery",
      status: "done",
      dueDate: day(-6, now),
      createdAt: iso(-40, 9, now),
      updatedAt: iso(-6, 9, now),
    },
    {
      id: "mls_mori_week",
      projectId: "prj_mori_calendar",
      name: "Weekly drop",
      status: "in_progress",
      dueDate: day(5, now),
      createdAt: iso(-7, 9, now),
      updatedAt: iso(-1, 9, now),
    },
    {
      id: "mls_coffee_board",
      projectId: "prj_coffee_menu",
      name: "Menu board lock",
      status: "pending",
      dueDate: day(21, now),
      createdAt: iso(-14, 9, now),
      updatedAt: iso(-12, 9, now),
    },
    {
      id: "mls_internal_scope",
      projectId: "prj_internal_os",
      name: "Floor scope",
      status: "in_progress",
      dueDate: day(12, now),
      createdAt: iso(-3, 9, now),
      updatedAt: iso(-1, 9, now),
    },
  ];

  const tasks: Task[] = [
    {
      id: "tsk_kobelco_access",
      projectId: "prj_kobelco_film",
      milestoneId: "mls_kobelco_shoot",
      title: "Confirm site access",
      description: "Induction slot and a named host on the day.",
      status: "blocked",
      assigneeId: "mem_julian",
      dueDate: day(1, now),
      priority: "urgent",
      createdAt: iso(-8, 9, now),
      updatedAt: iso(0, 8, now),
    },
    {
      id: "tsk_kobelco_shotlist",
      projectId: "prj_kobelco_film",
      milestoneId: "mls_kobelco_shoot",
      title: "Shot list for the excavator line",
      status: "in_progress",
      assigneeId: "mem_iris",
      dueDate: day(3, now),
      priority: "high",
      createdAt: iso(-8, 9, now),
      updatedAt: iso(-1, 9, now),
    },
    {
      id: "tsk_kobelco_grade",
      projectId: "prj_kobelco_stills",
      milestoneId: "mls_kobelco_stills",
      title: "Grade hero selects",
      status: "in_progress",
      assigneeId: "mem_nova",
      dueDate: day(8, now),
      priority: "normal",
      createdAt: iso(-5, 9, now),
      updatedAt: iso(-2, 9, now),
    },
    {
      id: "tsk_banwa_grade",
      projectId: "prj_banwa_film",
      milestoneId: "mls_banwa_rough",
      title: "Grade the water ritual",
      description: "Keep the stone warm. Do not crush the shadows.",
      status: "in_progress",
      assigneeId: "mem_nova",
      dueDate: day(1, now),
      priority: "high",
      createdAt: iso(-6, 9, now),
      updatedAt: iso(-1, 15, now),
    },
    {
      id: "tsk_banwa_music",
      projectId: "prj_banwa_film",
      milestoneId: "mls_banwa_rough",
      title: "Temp score pass",
      description: "A spare piano temp. No percussion.",
      status: "todo",
      assigneeId: "mem_iris",
      dueDate: day(3, now),
      priority: "normal",
      createdAt: iso(-6, 9, now),
      updatedAt: iso(-4, 9, now),
    },
    {
      id: "tsk_banwa_stills",
      projectId: "prj_banwa_content",
      milestoneId: "mls_banwa_week",
      title: "Select this week's stills",
      status: "in_progress",
      assigneeId: "mem_iris",
      dueDate: day(2, now),
      priority: "normal",
      createdAt: iso(-3, 9, now),
      updatedAt: iso(-1, 9, now),
    },
    {
      id: "tsk_visa_script",
      projectId: "prj_visa_explainer",
      milestoneId: "mls_visa_legal",
      title: "Chase marked-up script",
      description: "Legal has the cut. Picture lock does not move without it.",
      status: "blocked",
      assigneeId: "mem_julian",
      dueDate: day(0, now),
      priority: "urgent",
      createdAt: iso(-7, 9, now),
      updatedAt: iso(-1, 11, now),
    },
    {
      id: "tsk_visa_captions",
      projectId: "prj_visa_explainer",
      milestoneId: "mls_visa_lock",
      title: "Caption pass",
      status: "todo",
      assigneeId: "mem_nova",
      dueDate: day(8, now),
      priority: "normal",
      createdAt: iso(-7, 9, now),
      updatedAt: iso(-6, 9, now),
    },
    {
      id: "tsk_bp_cutdown",
      projectId: "prj_bp_promo",
      milestoneId: "mls_bp_cuts",
      title: "Finish the 6s cutdown",
      status: "in_progress",
      assigneeId: "mem_nova",
      dueDate: day(0, now),
      priority: "high",
      createdAt: iso(-5, 9, now),
      updatedAt: iso(-2, 15, now),
    },
    {
      id: "tsk_bp_endcard",
      projectId: "prj_bp_promo",
      milestoneId: "mls_bp_cuts",
      title: "Price end card",
      status: "todo",
      assigneeId: "mem_iris",
      dueDate: day(1, now),
      priority: "normal",
      createdAt: iso(-5, 9, now),
      updatedAt: iso(-3, 9, now),
    },
    {
      id: "tsk_bp_statics",
      projectId: "prj_bp_ads",
      milestoneId: "mls_bp_ads",
      title: "Static variants",
      status: "in_progress",
      assigneeId: "mem_iris",
      dueDate: day(6, now),
      priority: "normal",
      createdAt: iso(-3, 9, now),
      updatedAt: iso(-2, 12, now),
    },
    {
      id: "tsk_kendi_retouch",
      projectId: "prj_kendi_launch",
      milestoneId: "mls_kendi_portraits",
      title: "Light retouch on portraits",
      description: "Skin stays textured. Cleanup is dust and a stray hair only.",
      status: "in_progress",
      assigneeId: "mem_nova",
      dueDate: day(6, now),
      priority: "high",
      createdAt: iso(-4, 9, now),
      updatedAt: iso(-3, 13, now),
    },
    {
      id: "tsk_kendi_story",
      projectId: "prj_kendi_launch",
      milestoneId: "mls_kendi_film",
      title: "Opening-week story frames",
      status: "todo",
      assigneeId: "mem_iris",
      dueDate: day(12, now),
      priority: "normal",
      createdAt: iso(-4, 9, now),
      updatedAt: iso(-3, 9, now),
    },
    {
      id: "tsk_fivestar_scout",
      projectId: "prj_fivestar_films",
      milestoneId: "mls_fivestar_dawn",
      title: "Scout dawn angles",
      status: "todo",
      assigneeId: "mem_julian",
      dueDate: day(6, now),
      priority: "normal",
      createdAt: iso(-4, 9, now),
      updatedAt: iso(-4, 10, now),
    },
    {
      id: "tsk_crazy_notes",
      projectId: "prj_crazy_spots",
      milestoneId: "mls_crazy_review",
      title: "Log client review notes",
      status: "in_progress",
      assigneeId: "mem_julian",
      dueDate: day(1, now),
      priority: "high",
      createdAt: iso(-5, 9, now),
      updatedAt: iso(-1, 9, now),
    },
    {
      id: "tsk_mori_master",
      projectId: "prj_mori_menu",
      milestoneId: "mls_mori_delivered",
      title: "Deliver seasonal master",
      status: "done",
      assigneeId: "mem_nova",
      dueDate: day(-6, now),
      priority: "normal",
      createdAt: iso(-30, 9, now),
      updatedAt: iso(-6, 9, now),
    },
    {
      id: "tsk_mori_week",
      projectId: "prj_mori_calendar",
      milestoneId: "mls_mori_week",
      title: "Edit the weekly drop",
      status: "in_progress",
      assigneeId: "mem_nova",
      dueDate: day(4, now),
      priority: "normal",
      createdAt: iso(-2, 9, now),
      updatedAt: iso(-1, 9, now),
    },
    {
      id: "tsk_coffee_wait",
      projectId: "prj_coffee_menu",
      milestoneId: "mls_coffee_board",
      title: "Wait on the signed menu",
      status: "todo",
      assigneeId: "mem_julian",
      dueDate: day(20, now),
      priority: "low",
      createdAt: iso(-12, 9, now),
      updatedAt: iso(-12, 9, now),
    },
    {
      id: "tsk_internal_map",
      projectId: "prj_internal_os",
      milestoneId: "mls_internal_scope",
      title: "Map the floor screens",
      status: "in_progress",
      assigneeId: "mem_iris",
      dueDate: day(9, now),
      priority: "normal",
      createdAt: iso(-3, 9, now),
      updatedAt: iso(-1, 9, now),
    },
  ];

  const comments: TaskComment[] = [
    {
      id: "cmt_kobelco_access",
      taskId: "tsk_kobelco_access",
      authorId: "mem_julian",
      body: "Site office has not named a host. Shoot stays parked until they do.",
      createdAt: iso(0, 8, now),
    },
    {
      id: "cmt_visa_script",
      taskId: "tsk_visa_script",
      authorId: "mem_julian",
      body: "Legal has the cut. Asked again this morning. Do not picture-lock around them.",
      createdAt: iso(-1, 11, now),
    },
    {
      id: "cmt_banwa_grade",
      taskId: "tsk_banwa_grade",
      authorId: "mem_nova",
      body: "Rough cut is two days past the internal review. Grade is the remaining piece.",
      createdAt: iso(-1, 15, now),
    },
  ];

  const leads: Lead[] = [
    {
      id: "led_vesper",
      name: "Vesper Ceramics",
      company: "Vesper Ceramics",
      email: "hello@vesper.example",
      source: "referral",
      stage: "qualified",
      ownerId: "mem_iris",
      notes: "Wants a brand film for the spring collection.",
      createdAt: iso(-4, 9, now),
      updatedAt: iso(-4, 9, now),
    },
  ];

  const proposals: Proposal[] = [
    {
      id: "prp_vesper",
      leadId: "led_vesper",
      title: "Vesper brand film",
      status: "draft",
      amount: 18000,
      currency: "USD",
      summary: "Short film and stills for the spring collection.",
      createdAt: iso(-3, 9, now),
      updatedAt: iso(-2, 9, now),
    },
  ];

  const today = day(0, now);
  const mon = mondayOffset(now);

  function onWeekday(weekday: number): string {
    return day(mon + weekday, now);
  }

  function shootStatus(date: string, intent: "confirmed" | "hold" | "cancelled"): ShootStatus {
    if (intent === "cancelled") return "cancelled";
    if (date < today) return "wrapped";
    return intent;
  }

  const moriDate = onWeekday(-12);
  const coffeeDate = onWeekday(-8);
  const banwaRitualDate = onWeekday(-4);
  const kendiDate = onWeekday(0);
  const banwaStillsDate = onWeekday(1);
  const crazyDate = onWeekday(2);
  const fivestarDate = onWeekday(3);
  const kobelcoDate = onWeekday(4);
  const bpDate = onWeekday(5);
  const visaDate = onWeekday(8);
  const kobelcoStillsDate = onWeekday(11);

  const shoots: Shoot[] = [
    {
      id: "sht_mori_menu",
      clientId: "cli_mori",
      projectId: "prj_mori_menu",
      title: "Seasonal menu pickup",
      date: moriDate,
      callTime: "10:00",
      wrapTime: "15:00",
      location: "Mori & Mill, Salcedo Village, Makati",
      crewLeadId: "mem_iris",
      crewCount: 3,
      status: shootStatus(moriDate, "confirmed"),
      crewNotes: "Dining room stays as it serves. No styling beyond the plates already on the pass.",
      createdAt: iso(mon - 20, 9, now),
      updatedAt: iso(mon - 12, 16, now),
    },
    {
      id: "sht_coffee_menu",
      clientId: "cli_coffee",
      projectId: "prj_coffee_menu",
      title: "Menu board stills",
      date: coffeeDate,
      callTime: "08:30",
      location: "Coffee Dome, Kapitolyo, Pasig",
      crewLeadId: "mem_julian",
      crewCount: 2,
      status: "cancelled",
      crewNotes: "Paused with the client. Do not rebook until the menu board is signed.",
      createdAt: iso(mon - 14, 9, now),
      updatedAt: iso(mon - 8, 9, now),
    },
    {
      id: "sht_banwa_ritual",
      clientId: "cli_banwa",
      projectId: "prj_banwa_film",
      title: "Water ritual",
      date: banwaRitualDate,
      callTime: "07:30",
      wrapTime: "13:00",
      location: "Banwa Wellness Spa, Poblacion, Makati",
      crewLeadId: "mem_iris",
      crewCount: 4,
      status: shootStatus(banwaRitualDate, "confirmed"),
      crewNotes: "Quiet set. Natural light only. No voiceover, no playback in the treatment room.",
      createdAt: iso(mon - 10, 9, now),
      updatedAt: iso(mon - 4, 14, now),
    },
    {
      id: "sht_kendi_portraits",
      clientId: "cli_kendi",
      projectId: "prj_kendi_launch",
      title: "Opening portraits",
      date: kendiDate,
      callTime: "13:00",
      wrapTime: "17:30",
      location: "Kendi Beauty Lounge, BGC, Taguig",
      crewLeadId: "mem_iris",
      crewCount: 4,
      status: shootStatus(kendiDate, "confirmed"),
      crewNotes: "Skin stays textured. Cleanup later is dust and a stray hair, not a beauty pass.",
      createdAt: iso(mon - 6, 9, now),
      updatedAt: iso(mon, 9, now),
    },
    {
      id: "sht_banwa_stills",
      clientId: "cli_banwa",
      projectId: "prj_banwa_content",
      title: "Treatment room stills",
      date: banwaStillsDate,
      callTime: "08:00",
      wrapTime: "12:00",
      location: "Banwa Wellness Spa, Poblacion, Makati",
      crewLeadId: "mem_iris",
      crewCount: 3,
      status: shootStatus(banwaStillsDate, "confirmed"),
      crewNotes: "This week's always-on set. Stone, water, and the linen they actually use.",
      createdAt: iso(mon - 3, 9, now),
      updatedAt: iso(mon + 1, 8, now),
    },
    {
      id: "sht_crazy_pickup",
      clientId: "cli_crazy",
      projectId: "prj_crazy_spots",
      title: "Hero plate pickup",
      date: crazyDate,
      callTime: "11:00",
      wrapTime: "15:00",
      location: "Crazy Curry, Tomas Morato, Quezon City",
      crewLeadId: "mem_julian",
      crewCount: 4,
      status: shootStatus(crazyDate, "confirmed"),
      crewNotes: "Heat and color first. Shoot the curry before the lunch rush fills the room.",
      createdAt: iso(mon - 2, 9, now),
      updatedAt: iso(mon + 2, 10, now),
    },
    {
      id: "sht_fivestar_dawn",
      clientId: "cli_fivestar",
      projectId: "prj_fivestar_films",
      title: "Dawn exterior, villa one",
      date: fivestarDate,
      callTime: "05:15",
      wrapTime: "09:30",
      location: "Five Star Stays, Tagaytay Ridge",
      crewLeadId: "mem_julian",
      crewCount: 6,
      status: shootStatus(fivestarDate, "confirmed"),
      crewNotes: "Van leaves BGC at 03:30. Interiors only if the owner is off the property.",
      createdAt: iso(mon - 2, 11, now),
      updatedAt: iso(mon + 3, 8, now),
    },
    {
      id: "sht_kobelco_yard",
      clientId: "cli_kobelco",
      projectId: "prj_kobelco_film",
      title: "Excavator line, yard",
      date: kobelcoDate,
      callTime: "07:00",
      wrapTime: "16:00",
      location: "Kobelco yard, Calamba, Laguna",
      crewLeadId: "mem_julian",
      crewCount: 7,
      status: shootStatus(kobelcoDate, "hold"),
      crewNotes: "On hold for a named site host and the safety induction. Do not roll until access is confirmed.",
      createdAt: iso(mon - 5, 9, now),
      updatedAt: iso(0, 8, now),
    },
    {
      id: "sht_bp_ads",
      clientId: "cli_bp",
      projectId: "prj_bp_ads",
      title: "Standing offer, kitchen",
      date: bpDate,
      callTime: "09:00",
      wrapTime: "13:00",
      location: "BP Boiling Crabs & Shrimps, Kapitolyo, Pasig",
      crewLeadId: "mem_julian",
      crewCount: 4,
      status: shootStatus(bpDate, "confirmed"),
      crewNotes: "Steam, hands, and the price end card. Weekend service stays open around the set.",
      createdAt: iso(mon - 1, 9, now),
      updatedAt: iso(mon + 5, 9, now),
    },
    {
      id: "sht_visa_interview",
      clientId: "cli_visa_au",
      projectId: "prj_visa_explainer",
      title: "Partner interview",
      date: visaDate,
      callTime: "09:30",
      wrapTime: "13:00",
      location: "Visa Alliance, BGC, Taguig",
      crewLeadId: "mem_julian",
      crewCount: 4,
      status: shootStatus(visaDate, "confirmed"),
      crewNotes: "Plain language on camera. No legal claims until the marked-up script is back.",
      createdAt: iso(-4, 9, now),
      updatedAt: iso(-1, 11, now),
    },
    {
      id: "sht_kobelco_stills",
      clientId: "cli_kobelco",
      projectId: "prj_kobelco_stills",
      title: "Hero stills, studio",
      date: kobelcoStillsDate,
      callTime: "10:00",
      wrapTime: "18:00",
      location: "Lunarcore studio, Poblacion, Makati",
      crewLeadId: "mem_iris",
      crewCount: 3,
      status: shootStatus(kobelcoStillsDate, "confirmed"),
      crewNotes: "Neutral ground. Detail crops for the catalogue after the hero.",
      createdAt: iso(-6, 9, now),
      updatedAt: iso(-2, 9, now),
    },
  ];

  const reviews: Review[] = [
    {
      id: "rev_banwa_ritual",
      clientId: "cli_banwa",
      projectId: "prj_banwa_film",
      title: "Ritual film series",
      frameUrl: "https://next.frame.io/reviews/banwa-ritual-series",
      status: "in_review",
      notes: "Rough cut v3. The water grade is the open note.",
      createdAt: iso(-6, 9, now),
      updatedAt: iso(-1, 16, now),
    },
    {
      id: "rev_crazy_spots",
      clientId: "cli_crazy",
      projectId: "prj_crazy_spots",
      title: "Brand spots",
      frameUrl: "https://next.frame.io/reviews/crazy-curry-spots",
      status: "changes_requested",
      notes: "More heat in the first second, and hold the offer longer.",
      createdAt: iso(-5, 12, now),
      updatedAt: iso(-1, 9, now),
    },
    {
      id: "rev_visa_explainer",
      clientId: "cli_visa_au",
      projectId: "prj_visa_explainer",
      title: "Partner explainer",
      frameUrl: "https://next.frame.io/reviews/visa-alliance-explainer",
      status: "waiting",
      notes: "Link is up. Review waits on the marked-up script from legal.",
      createdAt: iso(-7, 9, now),
      updatedAt: iso(-1, 11, now),
    },
    {
      id: "rev_bp_promo",
      clientId: "cli_bp",
      projectId: "prj_bp_promo",
      title: "Weekend boil promo",
      frameUrl: "https://next.frame.io/reviews/bp-weekend-boil",
      status: "in_review",
      notes: "15s is in the review. The 6s follows the price end card.",
      createdAt: iso(-3, 9, now),
      updatedAt: iso(-2, 15, now),
    },
    {
      id: "rev_mori_menu",
      clientId: "cli_mori",
      projectId: "prj_mori_menu",
      title: "Seasonal menu film",
      frameUrl: "https://next.frame.io/reviews/mori-seasonal-menu",
      status: "approved",
      notes: "Approved with the delivery. Kept here as the record of the link.",
      createdAt: iso(-20, 9, now),
      updatedAt: iso(-6, 9, now),
    },
    {
      id: "rev_kendi_launch",
      clientId: "cli_kendi",
      projectId: "prj_kendi_launch",
      title: "Lounge launch",
      frameUrl: "https://next.frame.io/project/kendi-lounge-launch",
      status: "waiting",
      notes: "Project link only. Portraits are not in the review yet.",
      createdAt: iso(-4, 9, now),
      updatedAt: iso(-3, 13, now),
    },
    {
      id: "rev_kobelco_stills",
      clientId: "cli_kobelco",
      projectId: "prj_kobelco_stills",
      title: "Product stills",
      frameUrl: "https://next.frame.io/project/kobelco-product-stills",
      status: "waiting",
      notes: "Selects go up after the studio day. The yard film is still on hold.",
      createdAt: iso(-5, 9, now),
      updatedAt: iso(-2, 9, now),
    },
  ];

  return { members, clients, projects, milestones, tasks, comments, leads, proposals, shoots, reviews };
}
